In [3]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [8]:
def extract_oscar_table():
    url_oscars = "https://es.wikipedia.org/wiki/Premios_%C3%93scar"

    # Extract the Oscars table and store it in a DataFrame
    res_oscar = requests.get(url_oscars)

    # Check if the request was successful
    if res_oscar.status_code == 200:
        # Create BeautifulSoup object to access HTML content
        soup_oscar = BeautifulSoup(res_oscar.content, 'html.parser')

        # Find all tables with class 'wikitable'
        tables = soup_oscar.find_all("table", {"class": "wikitable"})

        if not tables:
            print("Error: No tables found with class 'wikitable'.")
            return (None, "No tables found with class 'wikitable'")

        # Select the first table (adjust if necessary)
        table_oscar = tables[0]

        # Get column names from the table
        columns = [th.getText().strip().lower() for th in table_oscar.find_all("th")]

        # Filter desired columns
        desired_columns = ['ceremonia', 'mejor película', 'mejor director', 'mejor actor', 'mejor actriz']
        column_indices = [columns.index(col) for col in desired_columns if col in columns]

        data = []
        # Traverse through table rows
        ceremony_found = False
        for row in table_oscar.find_all('tr'):
            # Get cells from the row
            cells = [td.getText().strip() for td in row.find_all("td")]

            # Check if we are at ceremony number 72 or later
            if cells and cells[0].startswith("72"):
                ceremony_found = True

            # If we have reached ceremony number 72, extract data
            if ceremony_found:
                # Check if there are enough cells in the row
                if len(cells) >= len(column_indices):
                    # Filter cells according to desired columns
                    filtered_cells = [cells[idx] for idx in column_indices]

                    # Aquí tomamos el string que obtenemos de la ceremonia en un año  y lo transformamos a interger.
                    ceremonia = filtered_cells[0]
                    anio_ceremonia = int(ceremonia[-4:])
                    filtered_cells[0] = anio_ceremonia

                    # Esta opción también funciona pero es abreviada de lo anterior.
                    # toma la primera celda filtrada y la reemplaza por los últimos cuatros carácteres de ella misma que coinciden con el año (empieza en la posición -4 porque son los 4 últimos dígitos)
                    # la primera celda es 24 de marzo del 2000 y la cambia por 2000
                    # filtered_cells[0] = int(filtered_cells[0][-4:])

                    # Ha continuación limpio los nombres de los directores, actores y actrices para sacar los parentesis y las peliculas dentro de ellos.
                    director = filtered_cells[2]
                    mejor_director = director.split('(')[0].strip() #Uso un split paradividir el string por el primer '(' que encuentra y uso el strip para eliminar espacios.
                    filtered_cells[2] = mejor_director

                    actor = filtered_cells[3]
                    mejor_actor = actor.split('(')[0].strip()
                    filtered_cells[3] = mejor_actor
                    
                    actriz = filtered_cells[4]
                    mejor_actriz = actriz.split('(')[0].strip()
                    filtered_cells[4] = mejor_actriz
                    
                    # Add data to the list only if valid and matching desired columns
                    if len(filtered_cells) == len(column_indices) and any(filtered_cells):
                        data.append(tuple(filtered_cells))
                        #print(len(data))

        if data:
            # Create DataFrame with filtered data and desired columns
            df = pd.DataFrame(data, columns=desired_columns)
            return (df, "Success")
        else:
            print("No data found starting from ceremony number 72.")
            return (None, "No data found starting from ceremony number 72.")

    else:
        print(f"Error: Request failed with status code {res_oscar.status_code}")
        return (None, f"Request failed with status code {res_oscar.status_code}")

# Extract Oscars table and store it in a tuple
oscar_results = extract_oscar_table()

# Check the type and content of the result
print(f"Result type: {type(oscar_results)}")
print("----------------------------------")
print(f"Result content: {oscar_results}")

# Ensure the tuple has exactly two elements
if isinstance(oscar_results, tuple) and len(oscar_results) == 2:
    # Unpack the tuple
    df_oscar, status = oscar_results

    # Display the first few rows of the resulting DataFrame if successful
    if df_oscar is not None:
        print(df_oscar.head())
    else:
        print(f"Error extracting table: {status}")
else:
    print("Error: The returned result is not a tuple with exactly two elements.")

Result type: <class 'tuple'>
----------------------------------
Result content: (    ceremonia                                   mejor película  \
0        2000                                  American Beauty
1        2001                                        Gladiator
2        2002                                 A Beautiful Mind
3        2003                                          Chicago
4        2004    The Lord of the Rings: The Return of the King
5        2005                              Million Dollar Baby
6        2006                                            Crash
7        2007                                     The Departed
8        2008                           No Country for Old Men
9        2009                              Slumdog Millionaire
10       2010                                  The Hurt Locker
11       2011                                The King's Speech
12       2012                                       The Artist
13       2013                                             Argo
14       2014                                 12 Years a Slave
15       2015  Birdman or (The Unexpected Virtue of Ignorance)
16       2016                                        Spotlight
17       2017                                        Moonlight
18       2018                               The Shape of Water
19       2019                                       Green Book
20       2020                                         Parasite
21       2021                                        Nomadland
22       2022                                             CODA
23       2023                Everything Everywhere All at Once
24       2024                                      Oppenheimer

          mejor director     mejor actor    mejor actriz
0              S. Mendes       K. Spacey        H. Swank
1          S. Soderbergh        R. Crowe      J. Roberts
2              R. Howard   D. Washington        H. Berry
3            R. Polanski        A. Brody       N. Kidman
4             P. Jackson         S. Penn       C. Theron
5            C. Eastwood         J. Foxx        H. Swank
6                 A. Lee   P. S. Hoffman  R. Witherspoon
7            M. Scorsese     F. Whitaker       H. Mirren
8        J. Coen E. Coen    D. Day-Lewis    M. Cotillard
9               D. Boyle         S. Penn      K. Winslet
10            K. Bigelow      J. Bridges      S. Bullock
11             T. Hooper        C. Firth      N. Portman
12       M. Hazanavicius     J. Dujardin       M. Streep
13                A. Lee    D. Day-Lewis     J. Lawrence
14             A. Cuarón  M. McConaughey    C. Blanchett
15        A. G. Iñárritu     E. Redmayne         J.Moore
16        A. G. Iñárritu     L. DiCaprio       B. Larson
17           D. Chazelle      C. Affleck        E. Stone
18           G. del Toro       G. Oldman    F. McDormand
19             A. Cuarón        R. Malek       O. Colman
20               Bong J.      J. Phoenix    R. Zellweger
21               C. Zhao      A. Hopkins    F. McDormand
22            J. Campion        W. Smith     J. Chastain
23  D. Kwan D. Scheinert       B. Fraser         M. Yeoh
24              C. Nolan       C. Murphy        E. Stone  , 'Success')
   ceremonia                                 mejor película mejor director  \
0       2000                                American Beauty      S. Mendes
1       2001                                      Gladiator  S. Soderbergh
2       2002                               A Beautiful Mind      R. Howard
3       2003                                        Chicago    R. Polanski
4       2004  The Lord of the Rings: The Return of the King     P. Jackson

     mejor actor mejor actriz
0      K. Spacey     H. Swank
1       R. Crowe   J. Roberts
2  D. Washington     H. Berry
3       A. Brody    N. Kidman
4        S. Penn    C. Theron

In [9]:
# Tabla
df_oscar

,ceremonia,mejor película,mejor director,mejor actor,mejor actriz
0,2000,American Beauty,S. Mendes,K. Spacey,H. Swank
1,2001,Gladiator,S. Soderbergh,R. Crowe,J. Roberts
2,2002,A Beautiful Mind,R. Howard,D. Washington,H. Berry
3,2003,Chicago,R. Polanski,A. Brody,N. Kidman
4,2004,The Lord of the Rings: The Return of the King,P. Jackson,S. Penn,C. Theron
5,2005,Million Dollar Baby,C. Eastwood,J. Foxx,H. Swank
6,2006,Crash,A. Lee,P. S. Hoffman,R. Witherspoon
7,2007,The Departed,M. Scorsese,F. Whitaker,H. Mirren
8,2008,No Country for Old Men,J. Coen E. Coen,D. Day-Lewis,M. Cotillard
9,2009,Slumdog Millionaire,D. Boyle,S. Penn,K. Winslet
10,2010,The Hurt Locker,K. Bigelow,J. Bridges,S. Bullock
11,2011,The King's Speech,T. Hooper,C. Firth,N. Portman
12,2012,The Artist,M. Hazanavicius,J. Dujardin,M. Streep
13,2013,Argo,A. Lee,D. Day-Lewis,J. Lawrence
14,2014,12 Years a Slave,A. Cuarón,M. McConaughey,C. Blanchett
15,2015,Birdman or (The Unexpected Virtue of Ignorance),A. G. Iñárritu,E. Redmayne,J.Moore
16,2016,Spotlight,A. G. Iñárritu,L. DiCaprio,B. Larson
17,2017,Moonlight,D. Chazelle,C. Affleck,E. Stone
18,2018,The Shape of Water,G. del Toro,G. Oldman,F. McDormand
19,2019,Green Book,A. Cuarón,R. Malek,O. Colman
20,2020,Parasite,Bong J.,J. Phoenix,R. Zellweger
21,2021,Nomadland,C. Zhao,A. Hopkins,F. McDormand
22,2022,CODA,J. Campion,W. Smith,J. Chastain
23,2023,Everything Everywhere All at Once,D. Kwan D. Scheinert,B. Fraser,M. Yeoh
24,2024,Oppenheimer,C. Nolan,C. Murphy,E. Stone